spring.application.name=Vantix_HRM
server.port=8080

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/Vantix_HRM
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# MAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=skmygamer662k7@gmail.com
spring.mail.password=nezb iyjv nhpa dkvy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT CONFIG
jwt.secret=vantix_hrm_super_secret_key_vantix_hrm_super_secret_key
jwt.expiration=86400000

cloudinary.cloud-name=dvzpxlhlb
cloudinary.api-key=932119712469187
cloudinary.api-secret=S5Oy9xctNrZbWYY59rplMYSG4TE

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# TIME KPI
spring.jackson.time-zone=GMT+7
spring.jpa.properties.hibernate.jdbc.time_zone=GMT+7